apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-app-monitor
  labels:
    release: prometheus
spec:
  endpoints:
  - port: "http"  
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: nodejs-app
