apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      serviceAccountName: vault-app-access
      containers:
      - name: nodejs-app
        image: rihab26/nodejs-app:90b8400
        ports:
        - containerPort: 3001
        - containerPort: 9090
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: connection_string
      - name: node-exporter
        image: rihab26/nodejs-app:90b8400
        ports:
        - containerPort: 9100