apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: rihab26/nodejs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://admin:securepassword123@mongo-service:27017"  # URI MongoDB avec le mot de passe
