apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-mongodb-access
  namespace: app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-app-access
  namespace: app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"